### ISSUE TITLE
Misuse of Bitcoin (capitalized) vs bitcoin (bitcoin) 

### ISSUE THREAD

**Issue by ThoAppelsin** [assafshomer/protocolu#10]
I was reading your documentation on [Introduction](../wiki/Introduction). The first paragraph introduces a convention to be used among the document, which is being violated by the end of the same paragraph as follows:

Bitcoin as a currency unit should have been written with a lowercase b according to that convention, but has been capitalized within the brackets at the very end.

This issue gives the impression to the careful reader that the documentation to come is likely going to be poor in quality, and otherwise is not critical at all.

**Comment by oleiba** [comment]
Hi @ThoAppelsin , there's a distinction between "Bitcoin" as the network\protocol notated with capital B, versus "bitcoins" as the amount of units of the underlying currency.
What's the issue?...

**Comment by ThoAppelsin** [comment]
Simply put, I believe:

> (1 Bitcoin = 100 million Satoshis)

should have been:

> (1 bitcoin = 100 million satoshis)

or maybe with Satoshis with capital S could also be fine, but not a Bitcoin with capital B.

**Comment by oleiba** [comment]
Modified to:

> 1 bitcoin = 100 million satoshis
