### ISSUE TITLE
Use IPFS multihash in the Coloring Scheme?

### ISSUE THREAD

**Issue by kulpreet** [assafshomer/protocolu#12]
Was going through the wiki pages about the "Coloring Scheme" and have a question about it.

https://github.com/Colored-Coins/Colored-Coins-Protocol-Specification/wiki/Coloring%20Scheme

Given that you are trying to solve the space constraints of OP_RETURN's 80 byte limit by using the 1|N mutisig approach, I was wondering why not use a simpler approach of storing all the asset manipulation instructions and the info_hash in IPFS (or equivalent)?

You could store the asset manipulation instructions and the info_hash on IPFS and then store the IPFS mutihash for that data in the OP_RETURN field of the transaction.

That will help solve the problems of Decentralization, Robustness, Ownership and Provable immutability as mentioned on your Benefits page https://github.com/Colored-Coins/Colored-Coins-Protocol-Specification/wiki/Benefits

If you talk about your reasons or motivations for your approach in any of your whitepapers or documents, could you please point me to it? I am eager to understand why why you went with 1) torrents over IPFS and 2) mutisig approach to solve space constraints over using an indirection through IPFS?

**Comment by tal-beja** [comment]
The motivation is simple, IPFS wasn't ready at the time of writing the specification

**Comment by kulpreet** [comment]
That is a very good reason 👍  Forgive my ignorance of the timelines here :)

Any plans to move the specs and or implementation to using IPFS/Freenet/Tahoe-LAFS?
