### ISSUE TITLE
Small typo in wiki

### ISSUE THREAD

**Issue by redsquirrel** [assafshomer/protocolu#6]
On this page: https://github.com/Colored-Coins/Colored-Coins-Protocol-Specification/wiki/Introduction

I think:

> Digital asset on top of the Bitcoin Blockchain...

should be:

> Digital assets on top of the Bitcoin Blockchain...

**Comment by redsquirrel** [comment]
Same page...

> This document describes the Colored Coins protocol specification for issuing and transacting digital asset... <== assets, right?

**Comment by assafshomer** [comment]
indeed. Thank you!
Fixed.
