### ISSUE TITLE
Issue 10 million units and transfer 2.5 million units to VC, which leaves 7,500,000 locked units

### ISSUE THREAD

**Issue by cnavigato** [assafshomer/protocolu#8]
"For example, let's return to the company from our previous example. The company can issue **750,000** units of a new unlocked asset, call it startup-x-round-B. This time each unit is redeemable for its proportion in the total amount of the new asset out of the existing **750,000** locked startup-x-to-the-moon. Initially each unit of the new asset is redeemable for exactly one unit of the old asset, but in case of a new round of funding the new asset can be diluted by issuing more units."

Should these numbers be 7,500,000 instead of 750,000?

**Comment by oleiba** [comment]
You are correct, fixed [with this revision](https://github.com/Colored-Coins/Colored-Coins-Protocol-Specification/wiki/Benefits/3bee1b6cfa73b0ce22f6fd77fb4933f338532c65)
